### ISSUE TITLE
License issues

### ISSUE THREAD

**Issue by makew0rld** [eaplmx/antenna-to-epub#2]
From https://text.eapl.mx/introducing-antennazine

> It's my first Open Sourced project in years. I'm open to fixing anything to comply with licenses

Sorry to report that there is a licensing issue here. [ebooklib](https://github.com/aerkalov/ebooklib) is AGPL licensed, which requires that any modules using it also be AGPL licensed. So either use a different lib, or switch to the AGPL license. I'd recommend the latter.

Technically this is a legal grey area, but best to be safe.

https://opensource.stackexchange.com/questions/6033/can-a-non-gpl-python-program-use-gpl-python-module

https://softwareengineering.stackexchange.com/questions/167773/how-does-the-gpl-static-vs-dynamic-linking-rule-apply-to-interpreted-languages

Happy holidays.

**Comment by eaplmx** [comment]
Thank you makeworld,
No worries, my idea is to be safe and comply with every license,

I'll take a look into switching to the AGPL license the next few days,
since I don't really know all the details right now, but looks like a nice
idea =)

Enjoy your holidays too!

**Comment by eaplmx** [comment]
Well, I changed the license from MIT to AGPL, same version ebooklib is using, which I think is good for this project.

Please check if with this change the project complies, otherwise I should research more on another license.
Thanks again!

**Comment by makew0rld** [comment]
Yep, looks good to me now!
